In [7]:
import libpysal
from giddy.markov import LISA_Markov
import numpy as np

In [8]:
f = libpysal.open(libpysal.examples.get_path("usjoin.csv"))
years = list(range(1929, 2010))
pci = np.array([f.by_col[str(y)] for y in years]).transpose()
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()
np.random.seed(10)
lm_random = LISA_Markov(pci, w, permutations=99)
r = lm_random.spillover()

In [41]:
f = libpysal.open(libpysal.examples.get_path("usjoin.csv"))
years = list(range(1929, 2010))
pci = np.array([f.by_col[str(y)] for y in years]).transpose()
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()
np.random.seed(0)
lm_random = LISA_Markov(pci, w, permutations=99)
r = lm_random.spillover()

In [42]:
r['components'][:,12]

array([0., 0., 0., 1., 0., 2., 2., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       2., 2., 0., 0., 0., 0., 0., 0., 1., 2., 2., 0., 2., 0., 0., 2., 0.,
       1., 2., 2., 0., 0., 0., 0., 0., 2., 0., 1., 2., 0., 0.])

In [43]:
rn = lm_random.spillover(neighbors_on=True)

In [45]:
rn["components"][:,13]

array([0., 1., 0., 1., 1., 2., 2., 0., 0., 1., 0., 2., 0., 0., 2., 0., 0.,
       2., 2., 2., 0., 0., 0., 1., 1., 1., 2., 2., 1., 2., 0., 1., 2., 0.,
       1., 2., 2., 0., 1., 0., 0., 1., 2., 2., 1., 2., 0., 1.])

In [51]:
np.random.seed(10)
lm_random = LISA_Markov(pci, w, permutations=99)
r = lm_random.spillover()
r['components'][:,12]

array([0., 0., 0., 1., 0., 2., 2., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       2., 2., 0., 0., 0., 0., 0., 0., 1., 2., 2., 0., 2., 0., 0., 2., 0.,
       1., 2., 2., 0., 0., 0., 0., 0., 2., 0., 1., 2., 0., 0.])

In [52]:
rn = lm_random.spillover(neighbors_on=True)
rn["components"][:,13]

array([0., 1., 0., 1., 1., 2., 2., 0., 0., 1., 0., 2., 0., 1., 2., 0., 2.,
       2., 2., 2., 0., 0., 0., 1., 1., 1., 2., 2., 1., 2., 0., 1., 2., 1.,
       1., 2., 2., 0., 1., 0., 1., 1., 2., 2., 1., 2., 0., 1.])

In [53]:
rn = lm_random.spillover(neighbors_on=True)
rn["components"][:,13]

array([0., 1., 0., 1., 1., 2., 2., 0., 0., 1., 0., 2., 0., 1., 2., 0., 2.,
       2., 2., 2., 0., 0., 0., 1., 1., 1., 2., 2., 1., 2., 0., 1., 2., 1.,
       1., 2., 2., 0., 1., 0., 1., 1., 2., 2., 1., 2., 0., 1.])

In [54]:
rn = lm_random.spillover(neighbors_on=True)
rn["components"][:,13]

array([0., 1., 0., 1., 1., 2., 2., 0., 0., 1., 0., 2., 0., 1., 2., 0., 2.,
       2., 2., 2., 0., 0., 0., 1., 1., 1., 2., 2., 1., 2., 0., 1., 2., 1.,
       1., 2., 2., 0., 1., 0., 1., 1., 2., 2., 1., 2., 0., 1.])

In [50]:
np.random.seed(10)
rn = lm_random.spillover(neighbors_on=True)
rn["components"][:,13]

array([0., 1., 0., 1., 1., 2., 2., 0., 0., 1., 0., 2., 0., 1., 2., 0., 2.,
       2., 2., 2., 0., 0., 0., 1., 1., 1., 2., 2., 1., 2., 0., 1., 2., 1.,
       1., 2., 2., 0., 1., 0., 1., 1., 2., 2., 1., 2., 0., 1.])